# AUTOGENERATED! DO NOT EDIT! File to edit: ..\00_grid.ipynb.

# %% auto 0
__all__ = ['Grid']

# %% ..\00_grid.ipynb 3
class Grid:
    def __init__(self, initial_value=None):
        if initial_value is not None:
            self.grid = initial_value
        else:
            self.grid=[]
            empty_row=[0,0,0,0,0]
            for i in range(5):
                self.grid.append(empty_row)

    def __repr__(self): 
        return f"Grid({str(self.grid)})"

    def __str__(self):
        s = '\r\n'.join([''.join(['{:3}'.format(item) for item in row]) for row in self.grid])
        return s
